"""LLM-driven extraction of structured eligibility criteria from trial text."""

from .extractor import (
    ExtractionResult,
    ExtractorError,
    ExtractorMissingParsedError,
    ExtractorRefusalError,
    extract_criteria,
)
from .prompt import PROMPT_VERSION, SYSTEM_PROMPT, build_messages
from .schema import (
    CRITERION_KINDS,
    AgeCriterion,
    ConditionCriterion,
    CriterionKind,
    EntityMention,
    EntityType,
    ExtractedCriteria,
    ExtractedCriterion,
    ExtractionMetadata,
    ExtractorRunMeta,
    FreeTextCriterion,
    MeasurementCriterion,
    MedicationCriterion,
    Polarity,
    SexCriterion,
    TemporalWindowCriterion,
    ThresholdOperator,
)

__all__ = [
    "CRITERION_KINDS",
    "PROMPT_VERSION",
    "SYSTEM_PROMPT",
    "AgeCriterion",
    "ConditionCriterion",
    "CriterionKind",
    "EntityMention",
    "EntityType",
    "ExtractedCriteria",
    "ExtractedCriterion",
    "ExtractionMetadata",
    "ExtractionResult",
    "ExtractorError",
    "ExtractorMissingParsedError",
    "ExtractorRefusalError",
    "ExtractorRunMeta",
    "FreeTextCriterion",
    "MeasurementCriterion",
    "MedicationCriterion",
    "Polarity",
    "SexCriterion",
    "TemporalWindowCriterion",
    "ThresholdOperator",
    "build_messages",
    "extract_criteria",
]
